apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq-uc-studentX
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: studentX
    server: 'https://kubernetes.default.svc'
  source:
    path: queue-manager-deployment/queue-managers
    repoURL: 'https://github.com/gomezrjo/mq-gitops-samples'
    targetRevision: main 
  project: default
